variable "environment" {
  description = "The environment for the deployment (e.g., dev, staging, prod)"
  type        = string
  default     = "prod"
}

variable "region" {
  description = "The AWS region to deploy resources"
  type        = string
  default     = "eu-central-1"
}

variable "alb_domain_name" {
  description = "The domain name for the API"
  type        = string
  default     = "alb.epic-trip-planner.com"
}

variable "hosted_zone_id" {
  description = "Route 53 Hosted Zone ID for example.com"
  type        = string
}

variable "blocked_bots_waf_cloudfront" {
  type    = list(string)
  default = ["Nikto", "SQLMap", "ZAP", "Hydra", "Masscan"]
}

variable "container_image" {
  description = "The Docker image (e.g. ECR URI)"
  type        = string
}

variable "allowed_origins" {
  description = "Allowed origins : list of domains which are explicitly permitted to access resources  in the context of Cross-Origin Resource Sharing (CORS)"
  type        = string
}

variable "cookie_secure_attribute" {
  description = "Cookie is visible for Http only"
  type        = bool
  default     = true
}

variable "cookie_same_site" {
  description = "Cookie same site"
  type        = string
  default     = "Lax"
}

variable "super_admin_fullname" {
  description = "Fullname of bootstrapped SuperAdmin user when app starts"
  type        = string
}

variable "notification_email" {
  description = "Email address for notifications"
  type        = string
}

#-------------- Image uploader variables -----------------------------------------------
variable "api_image_upload_domain_name" {
  description = "The domain name for the API to get pre-signed image upload URLs"
  type        = string
  default     = "api-image-upload.epic-trip-planner.com"
}

variable "backend_certificate_arn" {
  description = "The ARN of the ACM certificate for the ALB HTTPS listener and API Gateway"
  type        = string
}

variable "use_bucketav" {
  description = "Use BucketAV to prevent malware to be uploaded in S3 bucket"
  type        = bool
  default     = true
}

variable "bucketav_sns_findings_topic_name" {
  description = "Name of SNS topics where BucketAV publishes findings"
  type        = string
}

variable "uploads_bucket_name" {
  description = "The name of the S3 bucket for file uploads"
  type        = string
  default     = "uploads-bucket"
}

variable "enable_transfer_acceleration" {
  type        = bool
  description = "Enable S3 Transfer Acceleration?"
  default     = false
}

variable "lambda_upload_presigned_url_expiration_time_s" {
  description = "Expiration time in seconds for the pre-signed URL generated by the upload Lambda function"
  type        = number
  default     = 300
}

variable "lambda_memory_size_mb" {
  description = "Memory size in MB value for Lambda processing file which allow faster execution"
  type        = number
  default     = 512
}

variable "dynamodb_partition_key" {
  description = "DynamoDB partition key"
  type        = string
  default     = "user_id"
}

variable "dynamodb_sort_key" {
  description = "DynamoDB sort key"
  type        = string
  default     = "file_key"
}
